"""production readiness foundation

Revision ID: 4c32f08ab9a0
Revises: dd4475f105f2
Create Date: 2026-10-01 22:46:41.034484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c32f08ab9a0'
down_revision: Union[str, Sequence[str], None] = 'dd4475f105f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=40), nullable=False),
    sa.Column('identifier', sa.String(length=320), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation', 'identifier', name='uq_auth_rate_limit_key')
    )
    op.create_table('refresh_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.String(length=64), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('workflow_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Enum('ANALYSIS', 'AI_REVIEW', name='workflowjobtype', native_enum=False), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('dedupe_key', sa.String(length=160), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='workflowjobstatus', native_enum=False), nullable=False),
    sa.Column('progress_stage', sa.String(length=80), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=120), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['workflow_analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_jobs_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_jobs_available_at'), ['available_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_jobs_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_jobs_dedupe_key'), ['dedupe_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_workflow_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_jobs_status'), ['status'], unique=False)

    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_adjuster_user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_claims_assigned_adjuster_user_id'), ['assigned_adjuster_user_id'], unique=False)
        batch_op.create_foreign_key('fk_claims_assigned_adjuster_user_id', 'users', ['assigned_adjuster_user_id'], ['id'])

    op.execute(
        "UPDATE claims SET assigned_adjuster_user_id = "
        "(SELECT MIN(id) FROM users WHERE role = 'ADJUSTER' AND is_active = true) "
        "WHERE assigned_adjuster_user_id IS NULL"
    )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth_version', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('mfa_secret_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('mfa_recovery_codes_json', sa.Text(), nullable=False, server_default='[]'))

    # Databases created before AI Review reruns used one-result unique indexes.
    op.execute("DROP INDEX IF EXISTS ix_copilot_conclusions_analysis_id")
    op.create_index('ix_copilot_conclusions_analysis_id', 'copilot_conclusions', ['analysis_id'])
    op.execute("DROP INDEX IF EXISTS ix_workflow_ai_reviews_analysis_run_id")
    op.create_index('ix_workflow_ai_reviews_analysis_run_id', 'workflow_ai_reviews', ['analysis_run_id'])
    with op.batch_alter_table('workflow_ai_reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_job_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_workflow_ai_reviews_source_job_id'), ['source_job_id'], unique=True)
        batch_op.create_foreign_key(
            'fk_workflow_ai_reviews_source_job_id',
            'workflow_jobs',
            ['source_job_id'],
            ['id'],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_ai_reviews', schema=None) as batch_op:
        batch_op.drop_constraint('fk_workflow_ai_reviews_source_job_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_workflow_ai_reviews_source_job_id'))
        batch_op.drop_column('source_job_id')

    op.execute("DROP INDEX IF EXISTS ix_workflow_ai_reviews_analysis_run_id")
    op.create_index(
        'ix_workflow_ai_reviews_analysis_run_id',
        'workflow_ai_reviews',
        ['analysis_run_id'],
        unique=True,
    )
    op.execute("DROP INDEX IF EXISTS ix_copilot_conclusions_analysis_id")
    op.create_index(
        'ix_copilot_conclusions_analysis_id',
        'copilot_conclusions',
        ['analysis_id'],
        unique=True,
    )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mfa_recovery_codes_json')
        batch_op.drop_column('mfa_secret_encrypted')
        batch_op.drop_column('mfa_enabled')
        batch_op.drop_column('auth_version')

    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_constraint('fk_claims_assigned_adjuster_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_claims_assigned_adjuster_user_id'))
        batch_op.drop_column('assigned_adjuster_user_id')

    with op.batch_alter_table('workflow_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_workflow_jobs_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_workflow_jobs_claim_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_jobs_available_at'))
        batch_op.drop_index(batch_op.f('ix_workflow_jobs_analysis_run_id'))

    op.drop_table('workflow_jobs')
    with op.batch_alter_table('refresh_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_family_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_sessions_expires_at'))

    op.drop_table('refresh_sessions')
    op.drop_table('auth_rate_limits')
    # ### end Alembic commands ###
