"""baseline current schema

Revision ID: dd4475f105f2
Revises:
Create Date: 2026-10-01 22:43:53.837031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd4475f105f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ADJUSTER', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('vehicle_manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_manufacturers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_manufacturers_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_manufacturers_name'), ['name'], unique=True)

    op.create_table('assessment_rule_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=False),
    sa.Column('old_confidence_threshold', sa.Float(), nullable=False),
    sa.Column('old_repair_max_percentage', sa.Float(), nullable=False),
    sa.Column('old_replacement_min_percentage', sa.Float(), nullable=False),
    sa.Column('new_confidence_threshold', sa.Float(), nullable=False),
    sa.Column('new_repair_max_percentage', sa.Float(), nullable=False),
    sa.Column('new_replacement_min_percentage', sa.Float(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assessment_rule_configurations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('repair_max_percentage', sa.Float(), nullable=False),
    sa.Column('replacement_min_percentage', sa.Float(), nullable=False),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='assessment_rule_configurations_singleton'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_number', sa.String(length=24), nullable=True),
    sa.Column('claimant_name', sa.String(length=120), nullable=False),
    sa.Column('vehicle_make', sa.String(length=80), nullable=False),
    sa.Column('vehicle_model', sa.String(length=80), nullable=False),
    sa.Column('vehicle_year', sa.Integer(), nullable=False),
    sa.Column('license_plate', sa.String(length=32), nullable=True),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ANALYZING', 'REVIEW_REQUIRED', 'AI_APPROVED', 'AI_REJECTED', 'FAILED', name='claimstatus', native_enum=False), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_claim_number'), ['claim_number'], unique=True)

    op.create_table('claim_incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_revision', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim_incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_incidents_claim_id'), ['claim_id'], unique=True)

    op.create_table('damage_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_number', sa.String(length=24), nullable=True),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('assessment', sa.Enum('NO_DAMAGE', 'REPAIR_LIKELY', 'REPLACEMENT_LIKELY', 'MANUAL_INSPECTION_REQUIRED', name='damageassessment', native_enum=False), nullable=False),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('damage_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_damage_analyses_analysis_number'), ['analysis_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_damage_analyses_claim_id'), ['claim_id'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('VEHICLE_DAMAGE_IMAGE', 'DAMAGE_ANNOTATION', 'VEHICLE_DAMAGE_ANNOTATION', 'ID_CARD', 'INSURANCE_POLICY', 'VEHICLE_REGISTRATION', 'DRIVER_LICENSE', 'OTHER_DOCUMENT', name='evidencecategory', native_enum=False), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_path')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_claim_id'), ['claim_id'], unique=False)

    op.create_table('other_document_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('other_document_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_other_document_groups_claim_id'), ['claim_id'], unique=False)

    op.create_table('workflow_analysis_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('input_revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'PARTIAL', 'FAILED', name='analysisrunstatus', native_enum=False), nullable=False),
    sa.Column('damage_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'PARTIAL', 'FAILED', name='analysisresultstatus', native_enum=False), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_analysis_runs_claim_id'), ['claim_id'], unique=False)

    op.create_table('confirmed_analysis_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('input_revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('READY', 'STALE', name='analysissnapshotstatus', native_enum=False), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['workflow_analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('confirmed_analysis_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_confirmed_analysis_snapshots_analysis_run_id'), ['analysis_run_id'], unique=True)

    op.create_table('copilot_conclusions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('GENERATED', 'FALLBACK', 'LLM_UNAVAILABLE', name='copilotconclusionstatus', native_enum=False), nullable=False),
    sa.Column('recommendation', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('fallback_summary', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('provider_model', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['damage_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copilot_conclusions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copilot_conclusions_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('damage_analysis_rule_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('confidence_threshold', sa.Float(), nullable=False),
    sa.Column('repair_max_percentage', sa.Float(), nullable=False),
    sa.Column('replacement_min_percentage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['damage_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('damage_analysis_rule_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_damage_analysis_rule_snapshots_analysis_id'), ['analysis_id'], unique=True)

    op.create_table('damage_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('source_evidence_id', sa.Integer(), nullable=False),
    sa.Column('annotated_evidence_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_part', sa.String(length=80), nullable=True),
    sa.Column('damage_type', sa.String(length=80), nullable=True),
    sa.Column('damage_percentage', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'NO_SIGNIFICANT_DAMAGE', name='damagedetectionstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['damage_analyses.id'], ),
    sa.ForeignKeyConstraint(['annotated_evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('damage_detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_damage_detections_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('damage_model_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('adapter_name', sa.String(length=80), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['damage_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('damage_model_outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_damage_model_outputs_analysis_id'), ['analysis_id'], unique=True)

    op.create_table('document_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('VEHICLE_DAMAGE_IMAGE', 'DAMAGE_ANNOTATION', 'VEHICLE_DAMAGE_ANNOTATION', 'ID_CARD', 'INSURANCE_POLICY', 'VEHICLE_REGISTRATION', 'DRIVER_LICENSE', 'OTHER_DOCUMENT', name='evidencecategory', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'PARTIAL', 'FAILED', name='analysisresultstatus', native_enum=False), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['workflow_analysis_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_analyses_analysis_run_id'), ['analysis_run_id'], unique=False)

    op.create_table('document_ocr_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('VEHICLE_DAMAGE_IMAGE', 'DAMAGE_ANNOTATION', 'VEHICLE_DAMAGE_ANNOTATION', 'ID_CARD', 'INSURANCE_POLICY', 'VEHICLE_REGISTRATION', 'DRIVER_LICENSE', 'OTHER_DOCUMENT', name='evidencecategory', native_enum=False), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'PARTIAL', 'FAILED', name='analysisresultstatus', native_enum=False), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('adapter_name', sa.String(length=80), nullable=True),
    sa.Column('adapter_metadata_json', sa.Text(), nullable=False),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['workflow_analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'evidence_id')
    )
    with op.batch_alter_table('document_ocr_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_ocr_results_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_ocr_results_evidence_id'), ['evidence_id'], unique=False)

    op.create_table('evidence_removals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence_removals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_removals_evidence_id'), ['evidence_id'], unique=True)

    op.create_table('other_document_group_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['other_document_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('other_document_group_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_other_document_group_evidence_evidence_id'), ['evidence_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_other_document_group_evidence_group_id'), ['group_id'], unique=False)

    op.create_table('reference_part_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('part_identity', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('source_name', sa.String(length=160), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('price_type', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('FOUND', 'UNAVAILABLE', name='referencepricestatus', native_enum=False), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['damage_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reference_part_prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reference_part_prices_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('workflow_analysis_damage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('damage_analysis_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['workflow_analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['damage_analysis_id'], ['damage_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_analysis_damage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_analysis_damage_analysis_run_id'), ['analysis_run_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_workflow_analysis_damage_damage_analysis_id'), ['damage_analysis_id'], unique=True)

    op.create_table('copilot_conclusion_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('conclusion_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('APPROVED', 'REJECTED', name='copilotconclusionreviewstatus', native_enum=False), nullable=False),
    sa.Column('reason_category', sa.Enum('DOCUMENT_INFORMATION_INCOMPLETE', 'DOCUMENT_INFORMATION_INCORRECT', 'DAMAGE_ASSESSMENT_ISSUE', 'DAMAGE_EVIDENCE_ISSUE', 'MISSING_EVIDENCE', 'INCORRECT_AI_CONCLUSION', 'OTHER', name='copilotconclusionrejectioncategory', native_enum=False), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['conclusion_id'], ['copilot_conclusions.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copilot_conclusion_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copilot_conclusion_reviews_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_copilot_conclusion_reviews_conclusion_id'), ['conclusion_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_copilot_conclusion_reviews_reviewer_user_id'), ['reviewer_user_id'], unique=False)

    op.create_table('copilot_review_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conclusion_id', sa.Integer(), nullable=False),
    sa.Column('review_json', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.String(length=80), nullable=False),
    sa.Column('schema_version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conclusion_id'], ['copilot_conclusions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copilot_review_outputs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copilot_review_outputs_conclusion_id'), ['conclusion_id'], unique=True)

    op.create_table('document_analysis_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_analysis_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('original_ai_value', sa.Text(), nullable=False),
    sa.Column('reviewed_value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('VALID', 'WARNING', name='documentfieldstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['document_analysis_id'], ['document_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_analysis_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_analysis_fields_document_analysis_id'), ['document_analysis_id'], unique=False)

    op.create_table('document_extraction_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('document_ocr_result_id', sa.Integer(), nullable=False),
    sa.Column('source_evidence_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.Enum('VEHICLE_DAMAGE_IMAGE', 'DAMAGE_ANNOTATION', 'VEHICLE_DAMAGE_ANNOTATION', 'ID_CARD', 'INSURANCE_POLICY', 'VEHICLE_REGISTRATION', 'DRIVER_LICENSE', 'OTHER_DOCUMENT', name='evidencecategory', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'PARTIAL', 'FAILED', name='analysisresultstatus', native_enum=False), nullable=False),
    sa.Column('prompt_version', sa.String(length=80), nullable=False),
    sa.Column('schema_version', sa.String(length=80), nullable=False),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['workflow_analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['document_ocr_result_id'], ['document_ocr_results.id'], ),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_ocr_result_id')
    )
    with op.batch_alter_table('document_extraction_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_extraction_results_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_extraction_results_document_ocr_result_id'), ['document_ocr_result_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_document_extraction_results_source_evidence_id'), ['source_evidence_id'], unique=False)

    op.create_table('document_field_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('document_ocr_result_id', sa.Integer(), nullable=False),
    sa.Column('source_evidence_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=80), nullable=False),
    sa.Column('prompt_version', sa.String(length=80), nullable=False),
    sa.Column('ocr_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('VALID', 'INVALID', 'UNCERTAIN', 'MISSING', 'LLM_UNAVAILABLE', name='fieldvalidationstatus', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['workflow_analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['document_ocr_result_id'], ['document_ocr_results.id'], ),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_ocr_result_id', 'field_key')
    )
    with op.batch_alter_table('document_field_validations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_field_validations_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_field_validations_document_ocr_result_id'), ['document_ocr_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_field_validations_source_evidence_id'), ['source_evidence_id'], unique=False)

    op.create_table('workflow_ai_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('conclusion_id', sa.Integer(), nullable=False),
    sa.Column('validity_percentage', sa.Integer(), nullable=False),
    sa.Column('review_status', sa.String(length=64), nullable=False),
    sa.Column('warnings_json', sa.Text(), nullable=False),
    sa.Column('evidence_references_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['workflow_analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['conclusion_id'], ['copilot_conclusions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_ai_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_ai_reviews_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_ai_reviews_conclusion_id'), ['conclusion_id'], unique=True)

    op.create_table('claim_consistency_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('field_validation_id', sa.Integer(), nullable=False),
    sa.Column('source_evidence_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=80), nullable=False),
    sa.Column('claim_value', sa.Text(), nullable=False),
    sa.Column('document_value', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('MATCH', 'MISMATCH', 'UNAVAILABLE', name='consistencystatus', native_enum=False), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['workflow_analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['field_validation_id'], ['document_field_validations.id'], ),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_run_id', 'field_validation_id')
    )
    with op.batch_alter_table('claim_consistency_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_consistency_checks_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_consistency_checks_field_validation_id'), ['field_validation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claim_consistency_checks_source_evidence_id'), ['source_evidence_id'], unique=False)

    op.create_table('copilot_conclusion_review_reversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('reverted_by_user_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('reverted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reverted_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['copilot_conclusion_reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('copilot_conclusion_review_reversions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_copilot_conclusion_review_reversions_reverted_by_user_id'), ['reverted_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_copilot_conclusion_review_reversions_review_id'), ['review_id'], unique=True)

    op.create_table('document_extracted_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_run_id', sa.Integer(), nullable=False),
    sa.Column('extraction_result_id', sa.Integer(), nullable=False),
    sa.Column('source_evidence_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=80), nullable=False),
    sa.Column('ai_extracted_value', sa.Text(), nullable=True),
    sa.Column('confirmed_value', sa.Text(), nullable=True),
    sa.Column('prompt_version', sa.String(length=80), nullable=False),
    sa.Column('schema_version', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['workflow_analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['extraction_result_id'], ['document_extraction_results.id'], ),
    sa.ForeignKeyConstraint(['source_evidence_id'], ['evidence.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extraction_result_id', 'field_key')
    )
    with op.batch_alter_table('document_extracted_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_extracted_fields_analysis_run_id'), ['analysis_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_extracted_fields_extraction_result_id'), ['extraction_result_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_extracted_fields_source_evidence_id'), ['source_evidence_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_extracted_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_extracted_fields_source_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_document_extracted_fields_extraction_result_id'))
        batch_op.drop_index(batch_op.f('ix_document_extracted_fields_analysis_run_id'))

    op.drop_table('document_extracted_fields')
    with op.batch_alter_table('copilot_conclusion_review_reversions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copilot_conclusion_review_reversions_review_id'))
        batch_op.drop_index(batch_op.f('ix_copilot_conclusion_review_reversions_reverted_by_user_id'))

    op.drop_table('copilot_conclusion_review_reversions')
    with op.batch_alter_table('claim_consistency_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_consistency_checks_source_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_claim_consistency_checks_field_validation_id'))
        batch_op.drop_index(batch_op.f('ix_claim_consistency_checks_analysis_run_id'))

    op.drop_table('claim_consistency_checks')
    with op.batch_alter_table('workflow_ai_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_ai_reviews_conclusion_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_ai_reviews_analysis_run_id'))

    op.drop_table('workflow_ai_reviews')
    with op.batch_alter_table('document_field_validations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_field_validations_source_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_document_field_validations_document_ocr_result_id'))
        batch_op.drop_index(batch_op.f('ix_document_field_validations_analysis_run_id'))

    op.drop_table('document_field_validations')
    with op.batch_alter_table('document_extraction_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_extraction_results_source_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_document_extraction_results_document_ocr_result_id'))
        batch_op.drop_index(batch_op.f('ix_document_extraction_results_analysis_run_id'))

    op.drop_table('document_extraction_results')
    with op.batch_alter_table('document_analysis_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_analysis_fields_document_analysis_id'))

    op.drop_table('document_analysis_fields')
    with op.batch_alter_table('copilot_review_outputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copilot_review_outputs_conclusion_id'))

    op.drop_table('copilot_review_outputs')
    with op.batch_alter_table('copilot_conclusion_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copilot_conclusion_reviews_reviewer_user_id'))
        batch_op.drop_index(batch_op.f('ix_copilot_conclusion_reviews_conclusion_id'))
        batch_op.drop_index(batch_op.f('ix_copilot_conclusion_reviews_claim_id'))

    op.drop_table('copilot_conclusion_reviews')
    with op.batch_alter_table('workflow_analysis_damage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_analysis_damage_damage_analysis_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_analysis_damage_analysis_run_id'))

    op.drop_table('workflow_analysis_damage')
    with op.batch_alter_table('reference_part_prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reference_part_prices_analysis_id'))

    op.drop_table('reference_part_prices')
    with op.batch_alter_table('other_document_group_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_other_document_group_evidence_group_id'))
        batch_op.drop_index(batch_op.f('ix_other_document_group_evidence_evidence_id'))

    op.drop_table('other_document_group_evidence')
    with op.batch_alter_table('evidence_removals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_removals_evidence_id'))

    op.drop_table('evidence_removals')
    with op.batch_alter_table('document_ocr_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_ocr_results_evidence_id'))
        batch_op.drop_index(batch_op.f('ix_document_ocr_results_analysis_run_id'))

    op.drop_table('document_ocr_results')
    with op.batch_alter_table('document_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_analyses_analysis_run_id'))

    op.drop_table('document_analyses')
    with op.batch_alter_table('damage_model_outputs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_damage_model_outputs_analysis_id'))

    op.drop_table('damage_model_outputs')
    with op.batch_alter_table('damage_detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_damage_detections_analysis_id'))

    op.drop_table('damage_detections')
    with op.batch_alter_table('damage_analysis_rule_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_damage_analysis_rule_snapshots_analysis_id'))

    op.drop_table('damage_analysis_rule_snapshots')
    with op.batch_alter_table('copilot_conclusions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_copilot_conclusions_analysis_id'))

    op.drop_table('copilot_conclusions')
    with op.batch_alter_table('confirmed_analysis_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_confirmed_analysis_snapshots_analysis_run_id'))

    op.drop_table('confirmed_analysis_snapshots')
    with op.batch_alter_table('workflow_analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_analysis_runs_claim_id'))

    op.drop_table('workflow_analysis_runs')
    with op.batch_alter_table('other_document_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_other_document_groups_claim_id'))

    op.drop_table('other_document_groups')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_claim_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('damage_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_damage_analyses_claim_id'))
        batch_op.drop_index(batch_op.f('ix_damage_analyses_analysis_number'))

    op.drop_table('damage_analyses')
    with op.batch_alter_table('claim_incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_incidents_claim_id'))

    op.drop_table('claim_incidents')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_claim_number'))

    op.drop_table('claims')
    op.drop_table('assessment_rule_configurations')
    op.drop_table('assessment_rule_changes')
    with op.batch_alter_table('vehicle_manufacturers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_manufacturers_name'))
        batch_op.drop_index(batch_op.f('ix_vehicle_manufacturers_is_active'))

    op.drop_table('vehicle_manufacturers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
